spring.application.name=proyecto-feria
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl/feria-https.p12
server.ssl.key-store-password=feria2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=feria-https
spring.datasource.url=jdbc:h2:file:./data/feria-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.qr.window-seconds=15
app.recover.key=RECUPERAR-2026
app.jwt.secret=CAMBIAR_EN_PRODUCCION_JWT_LARGO_QUE_SUPERE_32_BYTES_1234567890
app.jwt.expiration-minutes=720
